version: "3.9" # Specify the docker compose version
services: # Specify the services that you are running
  postgres:
    image: postgres:14.6
    ports:
      - "8081:5432"
    environment:
      POSTGRES_PASSWORD: admin123
      POSTGRES_USER: pguser1
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
#  redis:
#    image: "redis:alpine"
